import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";
import { type RouterOutputs } from '../utils/api';

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime"
import Image from "next/image";

dayjs.extend(relativeTime)

const Home: NextPage = () => {

  const CreatePostWizard = () => {
    const { user } = useUser()
    if (!user) return null;
    console.log(user, "the user")
    return (
      <div className="flex gap-4 w-full">
        <Image src={user.profileImageUrl}
          alt="Profile image"
          className="w-16 h-16 rounded-full"
          width={56}
          height={56}
        />
        <input placeholder="Type some emojis" className="bg-transparent grow outline-none" />
      </div>
    )
  }

  type PostWithUser = RouterOutputs["posts"]["getAll"][number]

  const PostView = (props: PostWithUser) => {
    const { post, author } = props;
    return (
      <div key={post.id} className="p-8 border-b border-slate-400 flex gap-3">
        <Image src={author.profileImageUrl}
          alt="Profile image"
          className="w-16 h-16 rounded-full"
          width={16}
          height={16}
        />
        <div className="flex flex-col">
          <div className="flex gap-2 text-slate-300">
            <span>{`@${author.username} `}</span>
            <span className="font-thin">{` . ${dayjs(post.createdAt).fromNow()}`}</span>
          </div>
          <span>{post.content}</span>
        </div>

      </div>
    )

  }

  const user = useUser();
  const { data, isLoading } = api.posts.getAll.useQuery();
  if (isLoading) return <div>Loading...</div>
  if (!data) return <div>No Data</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-slate-400 md:max-w-2xl border-x">
          <div className="border-b border-slate-400 p-4 flex">
            {!user.isSignedIn && <div className="flex justify-center"><SignInButton /></div>}
            {!!user.isSignedIn && <CreatePostWizard />}
          </div>

          <div className="flex flex-col">
            {[...data, ...data].map((fullPost) => (
              <PostView key={fullPost.post.id} {...fullPost} />
            ))}
          </div>
        </div>

      </main>
    </>
  );
};

export default Home;
